"""column time_limits in BookStatus

Revision ID: abdf47f6602f
Revises: f49ef05cd524
Create Date: 2021-04-27 15:14:41.834118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdf47f6602f'
down_revision = 'f49ef05cd524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_duration', sa.Interval(), server_default='99999', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_status', schema=None) as batch_op:
        batch_op.drop_column('status_duration')

    # ### end Alembic commands ###
